### ISSUE TITLE
Exception in the release x64 build

### ISSUE THREAD

**Issue by nuiwos** [Microsoft/Windows-Machine-Learning#13]
The release x64 build hit a runtime exception. The debug x64 build did not hit this exception. Ran it on Windows 10.0.17134.48. Exception occurred after writing a digit and clicking on the recognize button.

System.Runtime.InteropServices.MissingInteropDataException
  HResult=0x80131500
  Message=ComTypeMarshalling_MissingInteropData, System.Collections.Generic.IList<System.Single>. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by shuweihsu** [comment]
`
int a;

int b;
`

**Comment by shuweihsu** [comment]
Hi,

Could you try add the following line to Default.rd.xml? It should solve the problem.

```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <!--
      An Assembly element with Name="*Application*" applies to all assemblies in
      the application package. The asterisks are not wildcards.
    -->
    <Assembly Name="*Application*" Dynamic="Required All" />
    
    <Type Name="System.Collections.Generic.IEnumerable{}" MarshalObject="Required All"/>
    
    
    <!-- Add your application specific runtime directives here. -->


  </Application>
</Directives>

```

**Comment by shuweihsu** [comment]
Hi,
Could you please add the following line to Default.rd.xml? It should resolve the problem.
**Type Name="System.Collections.Generic.IEnumerable{}" MarshalObject="Required All"/**

<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    
    <Assembly Name="*Application*" Dynamic="Required All" />
    
    <Type Name="System.Collections.Generic.IEnumerable{}" MarshalObject="Required All"/>
    
    
    


  </Application>
</Directives>

**Comment by nuiwos** [comment]
Added the line to Default.rd.xml and rebuilt solution. Issue not resolved. Exception still occurred.

**Comment by shuweihsu** [comment]
Could you please try this too?
Right click on MNIST_Demo project -> Properties -> un-check "Compile with .NET Native tool chain"

Thanks!

**Comment by nuiwos** [comment]
That resolved the issue. Thanks!

**Comment by shuweihsu** [comment]
Thanks for reporting the issue!  I'll create a pull request to fix this in project files.
